---
title: "Example of WISP.data functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example of WISP.data functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author: "Alessandro Oggioni"
---

## Provide the account of your station
```{r echo = T, results = 'hide', warning=FALSE}
userid <- Sys.getenv("WISP_IREA_USERID")
pwd <- Sys.getenv("WISP_IREA_PSW")
```

## Get data from the WISP station server for a multiple dates

If you want to download the data for a single date, consider using the function `wisp_get_reflectance_data()` instead.

```{r echo = T, results = 'hide', warning=FALSE}
reflect_data <- WISP.data::wisp_get_reflectance_multi_data(
  time_from = "2024-04-08T09:00",
  time_to = "2024-04-10T14:00",
  station = "WISPstation012",
  userid = userid,
  pwd = pwd
)
```

## Quality Check (QC) and Sunglint Removal (SR) of the reflectance data
```{r echo = T, results = 'hide', warning=FALSE}
reflect_data_qc <- WISP.data::wisp_qc_reflectance_data(
  data = reflect_data,
  maxPeak = 0.05
)
reflect_data_sr <- WISP.data::wisp_sr_reflectance_data(
  qc_data = reflect_data_qc
)
```

## Plot the reflectance data
```{r, warning=FALSE, out.width="100%"}
WISP.data::wisp_plot_reflectance_data(data = reflect_data_sr)
```
